/**
 * Cokomo Public Api
 * ## 👉 [Please see the CoKoMo documentation for more information.](https://cokomo-it.de/docs/start/api/documentation/)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CompetenceBase from '../model/CompetenceBase';
import Neighbour from '../model/Neighbour';

/**
* CompetenceBase service.
* @module api/CompetenceBaseApi
* @version 1.0.0
*/
export default class CompetenceBaseApi {

    /**
    * Constructs a new CompetenceBaseApi. 
    * @alias module:api/CompetenceBaseApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the competenceBaseIdDetailsGet operation.
     * @callback module:api/CompetenceBaseApi~competenceBaseIdDetailsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompetenceBase} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/CompetenceBaseApi~competenceBaseIdDetailsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompetenceBase}
     */
    competenceBaseIdDetailsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling competenceBaseIdDetailsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = CompetenceBase;
      return this.apiClient.callApi(
        '/CompetenceBase/{id}/details', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the competenceBaseIdGet operation.
     * @callback module:api/CompetenceBaseApi~competenceBaseIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompetenceBase} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/CompetenceBaseApi~competenceBaseIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompetenceBase}
     */
    competenceBaseIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling competenceBaseIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = CompetenceBase;
      return this.apiClient.callApi(
        '/CompetenceBase/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the competenceBaseIdNeighboursGet operation.
     * @callback module:api/CompetenceBaseApi~competenceBaseIdNeighboursGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Neighbour} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Number} [depth = 10)] 
     * @param {module:api/CompetenceBaseApi~competenceBaseIdNeighboursGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Neighbour}
     */
    competenceBaseIdNeighboursGet(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling competenceBaseIdNeighboursGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'depth': opts['depth']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = Neighbour;
      return this.apiClient.callApi(
        '/CompetenceBase/{id}/neighbours', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
