/**
 * Cokomo Public Api
 * ## 👉 [Please see the CoKoMo documentation for more information.](https://cokomo-it.de/docs/start/api/documentation/)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Metamodel from '../model/Metamodel';

/**
* Metamodel service.
* @module api/MetamodelApi
* @version 1.0.0
*/
export default class MetamodelApi {

    /**
    * Constructs a new MetamodelApi. 
    * @alias module:api/MetamodelApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the metamodelGet operation.
     * @callback module:api/MetamodelApi~metamodelGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Metamodel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/MetamodelApi~metamodelGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Metamodel}
     */
    metamodelGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = Metamodel;
      return this.apiClient.callApi(
        '/Metamodel', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
