/**
 * Cokomo Public Api
 * ## 👉 [Please see the CoKoMo documentation for more information.](https://cokomo-it.de/docs/start/api/documentation/)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoKoMoJavascriptClient);
  }
}(this, function(expect, CoKoMoJavascriptClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoKoMoJavascriptClient.Metamodel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Metamodel', function() {
    it('should create an instance of Metamodel', function() {
      // uncomment below and update the code to test Metamodel
      //var instance = new CoKoMoJavascriptClient.Metamodel();
      //expect(instance).to.be.a(CoKoMoJavascriptClient.Metamodel);
    });

    it('should have the property competenceBaseTypes (base name: "competenceBaseTypes")', function() {
      // uncomment below and update the code to test the property competenceBaseTypes
      //var instance = new CoKoMoJavascriptClient.Metamodel();
      //expect(instance).to.be();
    });

    it('should have the property edgeTypes (base name: "edgeTypes")', function() {
      // uncomment below and update the code to test the property edgeTypes
      //var instance = new CoKoMoJavascriptClient.Metamodel();
      //expect(instance).to.be();
    });

  });

}));
