/**
 * Cokomo Public Api
 * ## 👉 [Please see the CoKoMo documentation for more information.](https://cokomo-it.de/docs/start/api/documentation/)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoKoMoJavascriptClient);
  }
}(this, function(expect, CoKoMoJavascriptClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoKoMoJavascriptClient.CompetenceBaseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompetenceBaseApi', function() {
    describe('competenceBaseIdDetailsGet', function() {
      it('should call competenceBaseIdDetailsGet successfully', function(done) {
        //uncomment below and update the code to test competenceBaseIdDetailsGet
        //instance.competenceBaseIdDetailsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('competenceBaseIdGet', function() {
      it('should call competenceBaseIdGet successfully', function(done) {
        //uncomment below and update the code to test competenceBaseIdGet
        //instance.competenceBaseIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('competenceBaseIdNeighboursGet', function() {
      it('should call competenceBaseIdNeighboursGet successfully', function(done) {
        //uncomment below and update the code to test competenceBaseIdNeighboursGet
        //instance.competenceBaseIdNeighboursGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
